"""Regenerate docs/api/*.json and docs/API.md from the running code.

    python docs/api/generate_api_reference.py

Exports both services' OpenAPI specs, then writes a reference that marks every
endpoint by whether the web app calls it and whether a test exercises it. An
endpoint with neither is outside the MVP: present in the code, not relied on.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
API_DIR = ROOT / "docs" / "api"
METHODS = ["get", "post", "put", "patch", "delete"]
EXPORT = (
    "import json, logging; logging.disable(logging.CRITICAL); "
    "from app.main import app; print(json.dumps(app.openapi(), indent=2, sort_keys=True))"
)


def export(service: str) -> dict:
    out = subprocess.run([sys.executable, "-c", EXPORT], cwd=ROOT / service,
                         capture_output=True, text=True, check=True).stdout
    spec = json.loads(out)
    (API_DIR / f"{service}-openapi.json").write_text(json.dumps(spec, indent=2, sort_keys=True) + "\n",
                                                   encoding="utf-8")
    return spec


def corpus(folder: Path, patterns: tuple[str, ...], exclude: str | None = None) -> str:
    return "\n".join(
        p.read_text(encoding="utf-8", errors="replace")
        for pattern in patterns
        for p in folder.rglob(pattern)
        if "node_modules" not in p.parts and (exclude is None or exclude not in p.parts)
    )


def mentioned(path: str, text: str, prefix: str = "/api/v1") -> bool:
    """Whether a route appears in source, with or without the /api/v1 prefix (clients
    configured with a base URL leave it out), allowing any expression for each {param}."""
    routes = {path, path[len(prefix):]} if path.startswith(prefix) else {path}
    for route in routes:
        pattern = re.escape(route)
        pattern = re.sub(r"\\\{[^}]+\\\}", r"(?:\\$\\{[^}]+\\}|\\{[^}]+\\}|[\\w.-]+)", pattern)
        if re.search(pattern + r"(?![\w/])", text):
            return True
    return False


def section(title: str, spec: dict, app_text: str, test_text: str) -> list[str]:
    groups: dict[str, list[tuple[str, str, str, bool, bool]]] = defaultdict(list)
    for path, ops in spec["paths"].items():
        for method in METHODS:
            if method not in ops:
                continue
            op = ops[method]
            used = mentioned(path, app_text)
            tested = mentioned(path, test_text)
            groups[(op.get("tags") or ["service"])[0]].append(
                (path, method.upper(), op.get("summary", ""), used, tested))

    total = sum(len(v) for v in groups.values())
    mvp = sum(1 for v in groups.values() for e in v if e[3] or e[4])
    lines = [f"## {title}", "", f"{total} operations; {mvp} used by the app or covered by tests.", ""]
    for tag in sorted(groups):
        lines += [f"### {tag}", "", "| Method | Path | What it does | App | Tested |", "|---|---|---|---|---|"]
        for path, method, summary, used, tested in sorted(groups[tag]):
            lines.append(f"| `{method}` | `{path}` | {summary} | {'yes' if used else '—'} | {'yes' if tested else '—'} |")
        lines.append("")
    return lines


def main() -> None:
    backend, ai = export("backend"), export("ai-service")
    frontend_src = corpus(ROOT / "frontend" / "src", ("*.ts", "*.tsx"), exclude="tests")
    backend_tests = corpus(ROOT / "backend" / "app" / "tests", ("*.py",))
    backend_src = corpus(ROOT / "backend" / "app", ("*.py",), exclude="tests")  # the backend calls the AI service
    ai_tests = corpus(ROOT / "ai-service" / "app" / "tests", ("*.py",))
    demo_check = (ROOT / "backend" / "app" / "scripts" / "check_demo.py").read_text(encoding="utf-8") + \
        (ROOT / "backend" / "app" / "scripts" / "import_real_sprint.py").read_text(encoding="utf-8")

    lines = [
        "# API reference",
        "",
        "Generated by `python docs/api/generate_api_reference.py` from the services' own OpenAPI specs",
        "([backend](api/backend-openapi.json), [AI service](api/ai-service-openapi.json)). Interactive",
        "docs run at http://localhost:8000/docs and http://localhost:8001/docs.",
        "",
        "**App** — the web app calls it. **Tested** — a backend or AI-service test, or the demo check",
        "(`backend/app/scripts/check_demo.py`), exercises it. An endpoint with neither is **outside the",
        "MVP**: it is in the code from the original design (meetings, admin, organizational memory, the",
        "intelligence index, the review panel) but nothing in the product relies on it, and it should not",
        "be demonstrated as working.",
        "",
        "Every backend endpoint except `/health` and sign-in requires a bearer token, and every write is",
        "checked against the caller's role.",
        "",
    ]
    lines += section("Backend — http://localhost:8000", backend, frontend_src, backend_tests + demo_check)
    lines += section("AI service — http://localhost:8001", ai, backend_src, ai_tests)
    (ROOT / "docs" / "API.md").write_text("\n".join(lines), encoding="utf-8")
    print("wrote docs/API.md and docs/api/*.json")


if __name__ == "__main__":
    main()
